### ISSUE TITLE
JS error on Job Preview screen

### ISSUE THREAD

**Issue by ghobaty** [laravel/horizon#620]
- Horizon Version: 3.2.3
- Laravel Version: 5.7.28
- PHP Version: 7.2.19
- Redis Driver & Version: predis/predis 1.1.1
- Database Driver & Version: MySQL 5.7

### Description:
This happens for only some of our failed jobs. The preview screen keeps loading forever and there is a JS error in the console.
<img width="1678" alt="Screen Shot 2019-06-22 at 13 56 57" src="https://user-images.githubusercontent.com/6379163/59963627-27ac9c00-94f6-11e9-87c9-b72ab3d2e209.png">

**Comment by driesvints** [comment]
Does the bug prevents you from using any of the other JS functionality? (screen freezes)

**Comment by ghobaty** [comment]
No, it does not.

**Comment by ghobaty** [comment]
I've found that the error was with `phpunserialize`call on `payload.data.command`. I've also noticed this happens with there are unicode characters in the serialized string (e.g. `foo bar \ud83d baz`)

**Comment by driesvints** [comment]
@ghobaty does this still happen for you in the latest release?

**Comment by talvbansal** [comment]
I have something similar but a different error for random failed jobs. There seems to be nothing consistent between the jobs that behave like this but i'll get this exception is null error in the console. No retries or information about the job at all:

![Screenshot from 2019-10-22 10-23-55](https://user-images.githubusercontent.com/7305131/67273416-488df980-f4b6-11e9-85d5-ea75866f34cf.png)

**Comment by driesvints** [comment]
@talvbansal did you try republishing the assets when upgrading? https://laravel.com/docs/6.x/horizon#upgrading

**Comment by talvbansal** [comment]
@driesvints Hey! Thanks for looking at this, I did re-publish the assets prior to posting this and there were no changes so im not sure why this would happen.

I'm going to composer update and republish again and will report back on if i can still see this weird bug.

**Comment by talvbansal** [comment]
Managed to get another one

![Screenshot from 2019-10-29 10-04-31](https://user-images.githubusercontent.com/7305131/67757444-b9439180-fa33-11e9-8f16-ebea829f946f.png)

**Comment by themsaid** [comment]
I believe this is fixed in https://github.com/laravel/horizon/commit/9c3a75a0f3cc1a2d1805f48c8aab49469cb4ab33. Please upgrade to latest Horizon, re-publish the assets, and try again.

**Comment by ghobaty** [comment]
Running latest Horzion version, still getting a loading screen however no reported JS errors.

One thing I noticed but not sure if it is related is that the payload of all jobs whose detail pages fail to load contains unicode characters.

**Comment by ghobaty** [comment]
As an attempt to workaround this issue, we base64 encoded/decoded the unicode payload (i.e. job fields) and since then the issue has not happened again. FYI
